multi_user/accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views

urlpatterns = [
    
    path('login/', views.login_page, name='login'),
    path('', views.register_page, name='register'),
    path('profile/', views.profile_page, name='profile'),
    path('logout/', views.logout_user, name='logout'),


    path('blogs/', views.blogsall, name='blogs'),
    path('drafts/', views.drafts, name='drafts'),
    path('myblog/', views.myblogs, name='myblogs'),
    path('create/', views.createBlog, name='create'),
    path('mhealth/', views.mhealth, name='mhealth'),
    path('heartdis/', views.heartdis, name='heartdis'),
    path('covid19/', views.covid19, name='covid19'),
    path('immun/', views.immun, name='immun'),

    path('appoint/', views.appointment, name='appoint'),
    path('formapp/<int:pk>', views.create_appoint, name='appcreate'),
    path('myapps/', views.view_allapp, name='myapps'),
    
]

multi_user/multi_user/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

multi_user/accounts/forms.py
from accounts.models import MyUser, Blog, SPECIALITY,Appointment
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import EmailInput, PasswordInput


class RegisterForm(UserCreationForm):
    password1=forms.CharField(label='Password', widget=PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Confirm Password', widget=PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=MyUser
        fields=['username','email', 'first_name','last_name','password1','password2','address', 'city', 'pincode','state', 'profile_pic','patient', 'doctor']
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'passord':forms.PasswordInput(attrs={'class':'form-control'}),
            'address':forms.TextInput(attrs={'class':'form-control'}),
            'city':forms.TextInput(attrs={'class':'form-control'}),
            'pincode':forms.TextInput(attrs={'class':'form-control'}),
            'state':forms.Select(attrs={'class':'form-control'}),
            'patient':forms.CheckboxInput(attrs={'class':'form-check-input'}),
            'doctor':forms.CheckboxInput(attrs={'class':'form-check-input'}),
            'profile_pic':forms.FileInput(attrs={'class':'form-control'}),
            

        }
class LoginForm(forms.ModelForm):
    class Meta:
        model=MyUser
        fields=['username', 'password']
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'password':forms.PasswordInput(attrs={'class':'form-control'}),
            # 'password1':forms.PasswordInput(attrs={'class':'form-control'})
        }


CATEGORIES = (('Mental Health', 'Mental Health'),
              ('Heart Disease', 'Heart Disease'),
              ('COVID19', 'COVID19'),
              ('Immunization', 'Immunization'))


class BlogCreation(forms.ModelForm):
    title = forms.CharField(
        label='Title of the Blog: ', widget=forms.TextInput(attrs={'class': 'form-control'}))
    summary = forms.CharField(label='Summary of the Blog: ',
                              widget=forms.Textarea(attrs={'class': 'form-control'}))
    content = forms.CharField(label='Content of the Blog: ',
                              widget=forms.Textarea(attrs={'class': 'form-control'}))
    blog_category = forms.ChoiceField(choices=CATEGORIES,
                                      label='Select the Category', widget=forms.Select(attrs={'class': 'form-control'}))
    is_draft = forms.BooleanField(
        label=' Create Draft',
        required=False,
        initial=False)

    class Meta:
        model = Blog
        fields = ['title', 'summary',
                  'content','blog_image' ,'blog_category', 'is_draft']



class AppointmentCreation(forms.ModelForm):
    app_date = forms.DateField(label='Enter the date for the appointment: ',
                               widget=forms.DateInput(attrs={'class': 'form-control'}))
    app_time = forms.TimeField(
        label='Enter the time for the appointment: ', widget=forms.TimeInput(attrs={'class': 'form-control'}))
    speciality = forms.ChoiceField(choices=SPECIALITY,
                                   label='Required Speciality', widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Appointment
        fields = ['speciality', 'app_date', 'app_time']

multi_user/templates/appointment/appointform.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Appointment Form</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/CSS/navbarstyles.css">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
  <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />

</head>

<body id="body-pd">
          <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
              <a class="navbar-brand btn btn-outline-warning" href="{% url 'blogs' %}">All BLogs</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'myapps' %}">My appointment</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="{% url 'logout' %}">logout</a>
                  </li>
                  
                  <li class="nav-item">
                    <a class="nav-link active text-danger" >{{request.user.username}}</a>
                  </li>
                </ul>
             
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    {% if msg %}
    <div class="newcont mt-4 mb-0" style="width:205px;height: 100px;">   
            <div class="alert alert-danger alert-dismissible d-flex align-items-center fade show">
              <i class="bi-exclamation-octagon-fill"></i>
              <strong class="mx-2">Error!</strong>{{msg}}
              <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
      </div>
    {% endif %}

    <div class="container mx-3">
        <form action="" method="post" novalidate class="shadow p-5 mx-0" enctype="multipart/form-data">
    {% csrf_token %}
    <section class="vh-300 gradient-custom">
      <div class="container mt-0 mx-0 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card border border-info text-dark" style="border-radius: 1rem; width:500px;background-color: #009acd;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 pb-2">
                  <h2 class="fw-bold mb-2 text-uppercase">Book Your Appointment</h2>
                  <p class="text-dark-50 mb-5">Fill In Your Preferred Date and Time for the Appointment</p>

                    <label for="doctorName" class="dum sm-2"></label>Doctor's Name: </label>
                    <input class="form-control mt-2 mb-4" type="text" placeholder="{{doctor}}" readonly>

                    <label for="patientName" class="dum sm-2"></label>Patient's Name: </label>
                    <input class="form-control mt-2 mb-4" type="text" placeholder="{{request.user.first_name}}" readonly>

                    <label for="duration" class="dum sm-2"></label>Duration: </label>
                    <input class="form-control mt-2 mb-4" type="text" placeholder="45 minutes" readonly>

                  {% for fm in form %}
                  <div class="form-outline form-white mb-4">
                    <label class="form-label mt-2 mb-2">{{fm.label}}</label> {{fm}}
                    <small class="text-danger mt-2"> {{fm.errors|striptags}} </small>
                  </div>
                  {% endfor %}

                
                  <button class="btn btn-danger btn-md px-5 mt-4" type="submit">Create Appointment</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% if form.non_field_errors %} 
    {% for error in form.non_field_errors %}
      <p class="alert alert-danger my-3">{{error}}</p>
    {% endfor %}
  {% endif %}
  </form>
    </div>
</body>

  <script src="/static/JS/app.js"></script>

  <script>
    $(function () {
      $("#id_app_date").datepicker();
    });

    $('#id_app_time').timepicker({
        uiLibrary: 'bootstrap'
    });
    
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
            crossorigin="anonymous"></script>
</html>

multi_user/templates/appointment/appointment_1.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}myblog{% endblock title %}
{% block body %}
<br>

<div class="container text-center">
    <div class="row">
        <div class="col-sm-12 text-dark bg-warning border border-danger">
            <H3>Book your Appointment Here</H3>
        </div>
    </div>
    <br>

    <div class="container">
        {% for i in data %}

        <div class="card" width="300" height="200">
            <div class="card__header">
                {% if i.profile_pic %}
                <img src="{{ i.profile_pic.url }}" alt="card__image" class="card__image" >
                {% endif %}
            </div>
            <div class="card__body">
                <span class="tag tag-blue mb-3">{{i.city}}</span>
                <h5>Doctor Name: {{i.first_name}} {{i.last_name}}</h5>
                <a href="{% url 'appcreate' i.id  %}" class="btn btn-dark mx-5 mt-3" style="background-color:#24272E;">
                    Book An Appointment
                </a>
            </div>
        </div>

        <br>
        {% endfor %}
    </div>


    {% endblock body %}

multi_user/templates/appointment/viewappoint_1.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}myblog{% endblock title %}
{% block body %}
<br>

<div class="container text-center">
    <div class="row">
        <div class="col-sm-12 text-dark  border border-danger">
            <H3>Appointment Detail</H3>
        </div>
    </div>
    <br>

    <div class="container">
        {% for i in data %}
        <div class="card">
            <div class="card__body">
                <h4>Appointment {{forloop.counter}}</h4>
                <h5 class="text">Doctor's Name: {{i.doctor_name.first_name}}</h5>
                <h6 class="text">Appointment Date: {{i.app_date}}</h6>
                <h6 class="text">Appointment start time: {{i.app_time}}</h6>
                <h6 class="text">Appointment end time: {{i.end_time}}</h6>
            </div>
        </div>
        <br>
        
        {% endfor %}
    </div>


    {% endblock body %}